language: python
install: skip
script: 
  - echo "Threads/core $(nproc --all)"
  - free -g

jobs:
  include:
     - dist: focal
     - dist: focal
       vm:
         size: large
     - os: osx
       python: "2.7"
       script: python ./hello.py
     #- os: windows
     - os: freebsd
       script: python ./hello.py
     
