language: python
install: skip
script: python ./hello.py

jobs:
  include:
     - dist: focal
       before_install:
         - echo "Threads/core: $(nproc --all)"
         - free -g
     - dist: focal
       vm:
         size: large
       before_install:
         - echo "Threads/core: $(nproc --all)"
         - free -g
     - os: osx
       python: "2.7"
     #- os: windows
     - os: freebsd
     
